import fs from "node:fs";
import path from "node:path";

const projectRoot = process.cwd();
const inputDir = path.join(projectRoot, "src/data/spotify-history");
const outputFile = path.join(projectRoot, "src/data/demoSpotifyHistory.js");
const minMonthlyStreams = 3;

function readJsonFile(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function getMonthTimestamp(timestamp) {
  const month = String(timestamp || "").slice(0, 7);

  if (!/^\d{4}-\d{2}$/.test(month)) return "";

  return `${month}-15T12:00:00.000Z`;
}

function getSafeEntry(entry) {
  const timestamp = getMonthTimestamp(entry.ts);
  const trackName = String(entry.master_metadata_track_name || "").trim();
  const artistName = String(entry.master_metadata_album_artist_name || "").trim();
  const albumName = String(entry.master_metadata_album_album_name || "").trim();
  const msPlayed = Number(entry.ms_played || 0);

  if (!timestamp || !trackName || !artistName || !albumName || msPlayed <= 0) {
    return null;
  }

  return {
    timestamp,
    trackName,
    artistName,
    albumName,
    msPlayed,
  };
}

function aggregateHistory() {
  if (!fs.existsSync(inputDir)) {
    throw new Error(`Raw Spotify history directory does not exist: ${inputDir}`);
  }

  const jsonFiles = fs
    .readdirSync(inputDir)
    .filter((fileName) => fileName.endsWith(".json"))
    .sort();
  const aggregates = new Map();

  for (const fileName of jsonFiles) {
    const rows = readJsonFile(path.join(inputDir, fileName));

    for (const row of rows) {
      const safeEntry = getSafeEntry(row);

      if (!safeEntry) continue;

      const key = [
        safeEntry.timestamp,
        safeEntry.trackName,
        safeEntry.artistName,
        safeEntry.albumName,
      ].join("\u0001");
      const current = aggregates.get(key) || {
        ts: safeEntry.timestamp,
        streams: 0,
        total_ms_played: 0,
        master_metadata_track_name: safeEntry.trackName,
        master_metadata_album_artist_name: safeEntry.artistName,
        master_metadata_album_album_name: safeEntry.albumName,
      };

      current.streams += 1;
      current.total_ms_played += safeEntry.msPlayed;
      aggregates.set(key, current);
    }
  }

  return [...aggregates.values()]
    .filter((row) => row.streams >= minMonthlyStreams)
    .map((row) => ({
      ...row,
      total_ms_played: Math.round(row.total_ms_played),
    }))
    .sort((left, right) => {
      const dateComparison = left.ts.localeCompare(right.ts);

      if (dateComparison !== 0) return dateComparison;

      return `${left.master_metadata_album_artist_name} ${left.master_metadata_track_name}`.localeCompare(
        `${right.master_metadata_album_artist_name} ${right.master_metadata_track_name}`,
      );
    });
}

const demoHistory = aggregateHistory();
const output = `// Generated by scripts/buildDemoSpotifyHistory.mjs.
// This file contains sanitized, month-level aggregate demo rows only.
// It intentionally excludes raw Spotify export fields such as IP address,
// country, platform, exact play timestamps, username, and playback metadata.

export const demoSpotifyHistory = ${JSON.stringify(demoHistory)};
`;

fs.writeFileSync(outputFile, output);

console.log(
  `Wrote ${demoHistory.length.toLocaleString()} sanitized demo rows to ${path.relative(
    projectRoot,
    outputFile,
  )}`,
);
